[package]
name = "zombenum-client"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"

[dependencies]
zombenum-shared = { path = "../shared" }
macroquad = "0.3.0-alpha.14"
naia-client-socket = "0.5"
