language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libasound2-dev -qq

install:
  - wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - pushd SDL2-2.0.5 && ./configure --prefix=/usr && make && sudo make install && popd
