[package]
name = "zombenum"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>", "Tronje Krabbe <hi@tron.je>"]

[dependencies]
specs = "0.9.1"
ggez = "0.3.1"
serde_json = "1.0"
log = "0.3"
env_logger = "0.4.3"
