[package]
name = "zombenum-shared"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"

[dependencies]
legion = "0.3"
laminar = "0.4"
anyhow = "1"
bincode = "1"
glam = { version = "0.12", features = ["serde"] }

serde = "1"
